config/routes.rb
Rails.application.routes.draw do
  get 'contact_form/new'
  get 'contact_form/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/shop' => 'pages#shop'
  get '/flavors' => 'pages#flavors'

  resources :contact_forms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your.email@your.domain.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
  def new
      @contact_form = ContactForm.new
    end

    def create
      begin
        @contact_form = ContactForm.new(params[:contact_form])
        @contact_form.request = request
        if @contact_form.deliver
          flash.now[:notice] = 'Thank you for your message!'
        else
          flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
          render :new
        end  
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end	

	def shop
	end	

	def flavors
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact_form/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div

app/views/contact_form/new.html.erb
<br/>
<h1 align="center">ContactForm</h1>
<br/>
<div class="booyah-box col-5 offset-4" align="center">
	<br/>

  <%= simple_form_for @contact_form do |f| %>
	  <%=	f.input :name %>
	  <br/>
	  <%=	f.input :email %>
	  <br/>
	  <%=	f.input :message, :as => :text, :input_html => {:rows => 5} %>
	  <br/>
	  <br/>
  	<%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
  <% end %>	
  	<br/>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quinn Pie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, user-scalable=no">
  </head>

  <body>

  
  
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded ">


      <h3 style="margin-left: 40px;">Order Online</h3>

      <div align="center">
        <%= link_to image_tag('quinn2.png', style: 'height:180px; width: 180px;'), root_path, class: 'img-fluid, img-responsive offset-1' %>
      </div>  

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

     
        
     

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Bakery', flavors_path, class: 'link'%>
          </li>
          <li class="nav-item">
           <%= link_to 'Flowers', '#', class: 'link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Gifts', '#', class: 'link' %>
          </li>  
        </ul>
      </div>
    </nav>

    <%= yield %>

  </div>

    <div id="footer">
      <div class="align">
        <div class="row">
          <div class="col-5 offset-1 social">
          <br />
          <%= link_to '#' do %> 
            <span class="fa fa-github-square fa-3x social-button"></span>
          <% end %>
          <%= link_to '#' do %>  
            <span class="fa fa-facebook-square fa-3x social-button"></span>
          <% end %>
          <%= link_to '#' do %>
            <span class="fa fa-instagram fa-3x social-button"></span> 
          <% end %>    
        </div>


          <div class="col-5 offset-1" style="font-size: 23px;">
            <%= link_to 'Contact Us', contact_form_new_path %>
            <br/>
            <%= link_to 'Order Online', '#' %>
          </div>
        </div>
      </div>
    </div>
  
  </body>
</html>

app/views/pages/flavors.html.erb
<div class="flavors">
	<br/>
	<div class="row justify-content-around">
		<div class="col-lg-5 col-sm-10">
			<h3 align="center">Flavors</h3>
			<div class="cookies">
				<h4>Cookies</h4>
				<ul>
					<li>Chocolate Chip</li>
					<li>Peanut Butter</li>
					<li>Peanut Butter Chocolate Chip</li>
					<li>Snickerdoodle</li>
					<li>Mint Chocolate Chip</li>
					<li>White Chocolate Macadamia Nut</li>
				</ul>	
			</div>
			<div class="cake">
				<h4>Cupcakes</h4>
				<ul>
					<li>Chocolate Fudge</li>
					<li>Vanilla Bean</li>
					<li>Red Velvet</li>
					<li>Carrot</li>
					<li>Lemon</li>
					<li>Funfetti</li>
				</ul>
			</div>
			<div class="pie">
				<h4>Pies</h4>
				<ul>
				<li>Apple</li>	
				<li>Strawberry Reubarb</li>	
				<li>Blackberry</li>	
				<li>Olaberry</li>	
				<li>Pumpkin</li>	
				<li>Pecan</li>	
		</div>
		<div class="col-lg-5 col-sm-10">
			<h3 align="center">Gift Boxes</h3>
		</div>
	</div>
</div>			

app/views/pages/index.html.erb
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <%= image_tag 'chewy.jpg', class: 'img-fluid, img-responsive' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Explore our assortnment of goodies</h3>
        </div> 
      </div>

      <div class="carousel-item">
        <%= image_tag 'cupcakes.jpg', class: 'img-fluid, img-responsive' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Just one bite</h3>
        </div>
      </div>

      <div class="carousel-item">
        <%= image_tag 'berrypie.jpg', class: 'img-fluid, img-responsive' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Treat yourself to a slice of pie</h3>
        </div>  
      </div>

      <div class="carousel-item">
        <%= image_tag 'flower4.jpg', class: 'img-fluid, img-responsive' %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Stunning arrangements for any occasion</h3>
        </div>  
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

<br />
<br />


<br/>
  <div class="details">
    <div class="wall">
     <div class="container">
       <div class="row">
          <div class="col">
            <br/>
            <br/>
            <br/>
            <u><%= link_to 'Explore Our Bakery', flavors_path, class: 'home_links' %></u>
            <br/>
            <p>Enjoy our assortment of delicious goodies. All of our treats are baked fresh daily using locally sourced ingredients.</p>
          </div>
          <div class="col">
            <br/>
            <%= image_tag 'pastry.jpg', style: 'height:390px; width: 541px;' ,class: 'img-fluid' %>
          </div> 
        </div> 
      </div>     
      <br/>
    </div> 
  </div>   

     
          
    <br/>
    <br/>
      

    <div class="wall">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-lg-5">
            <br/>
            <%= image_tag 'color2.jpeg', style: 'height:390px; width: 541px;', class: 'img-fluid' %>
          </div>
          <div class="col-sm-12 col-lg-5">
            <br/>
            <br/>
            <br/>
            <u><%= link_to 'Find the Perfect Flower', '#', class: 'home_links' %></u>
            <br/>
            <p>Enjoy our assortment of delicious treats. All of our treats are baked fresh daily using locally sourced ingredients.</p>
          </div>  
        </div>
      </div> 
      <br/>
    </div> 
  </div>      

<br/>
<br/>
<br/>
<br/>
<br/>

<div class="mailing">
  <div class="container">
    <div class="row">
      <div class="col">
        <br/>
        <br/>
        <h1>Join our mailing list</h1>
        <br/>
        <p>Stay up to date on exclusive offers, giveaways, and seasonal goodies!</p>
        <div align="center">
          <%= link_to 'Subscribe', '#', class: "btn btn-primary" %>
        </div>
      </div>
      <div class="col">
        <br/>
        <br/>
        <%= image_tag 'mail.png', style: 'height:310px; width: 541px;', class: 'img-fluid' %>
      </div> 
    </div>
  </div> 
    <br/> 
    <br/>      
</div>  